Repository SCE-Development/SCE-CLI, pull requests merged in 2022-01, with the labels that each got.

#26 Refactored process for Windows Setup
  requirements.txt
  sce.py
  tools/setup.py
Labels: enhancement

#28 Update README
  README.md
Labels: documentation, enhancement

#29 Fix discord-bot setup script
  tools/setup.py
Labels: bug

#31 Adds Node installation checks
  tools/setup.py
Labels: enhancement

#33 Fixed SCE_PATH for Unix
  tools/setup.py
Labels: bug

#36 Removed line that wrote `dookie` alias to file
  tools/setup.py
Labels: enhancement
